[package]
name = "yremote"
version = "0.1.0"
authors = ["wjy <1875256338@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
